# 广播机制的充要条件    
1. 两个张量进行维度比较，从右向左比较；  
2. 两个张量同一纬度要么相等，要么其中一个为1（若维度缺失也看作维度是1）；  

首先，创造一个`1*4*3`的矩阵x   

In [8]:
import torch
x = torch.arange(12).reshape(1, 4, 3)
print(x)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])


其次，创造一个`2*2*1`的矩阵y

In [9]:
y = torch.arange(6).reshape(2, 1, 3)
print(y)

tensor([[[0, 1, 2]],

        [[3, 4, 5]]])


利用广播机制进行X+Y操作，注意三个维度均向大的一方扩展，并且每一维都满足双方整倍数关系

In [10]:
print(x+y)

tensor([[[ 0,  2,  4],
         [ 3,  5,  7],
         [ 6,  8, 10],
         [ 9, 11, 13]],

        [[ 3,  5,  7],
         [ 6,  8, 10],
         [ 9, 11, 13],
         [12, 14, 16]]])
